version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    network_mode: "host"
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: localhost
            database: graphqlPrisma
            user: postgres
            password: postgres
            rawAccess: true
            port: '5432'
            migrations: true